---
- hosts: _sltt
  become: true
  become_method: sudo

  tasks:
    - name: Install yum packages
      yum:
        state: latest
        name: "{{ packages }}"
      vars:
        packages:
        - git
        - nodejs
        - npm

    - name: install n (node version installer/switcher)
      npm: name=n state=present global=yes

    - name: install the latest stable version of node
      shell: n lts

    - name: Create web user
      user: name=web

    - name: Create sltt directories
      file: 
        group: web 
        owner: web 
        mode: 755 
        state: directory
        path: "{{ item }}"
      loop:
        - "/var/www/sltt"
        - "/var/www/sltt/projects"
        - "/var/www/sltt/videos"
        - "/var/www/sltt/log"

    - name: Install pm2
      npm: name=pm2 state=present global=yes

    - name: Install yarn
      npm: name=yarn state=present global=yes

