---
- hosts: _sltt
  become: true
  become_method: sudo
  vars:
    repository: https://github.com/sign-language-translation-tools/sltt.git
    sltt: /var/www/sltt

  tasks:
    - name: Install pm2
      npm: name=pm2 state=present global=yes

    - name: Install yarn
      npm: name=yarn state=present global=yes

    - name: Stop the service
      command: pm2 stop sltt
      ignore_errors: yes

    - name: Delete the service
      command: pm2 delete sltt
      ignore_errors: yes

    - name: Clone/Pull repo
      git:
        repo: "{{repository}}"
        dest: /var/www/sltt

    - name: Install server npm depenencies using yarn
      yarn: 
        path: "{{sltt}}/server"

    - name: Apply heartbeat timeout fix patch
      patch:
        src: "{{sltt}}/server/ansible/patches/fix_heartbeat_timeout"
        dest: "{{sltt}}/server/node_modules/express-pouchdb/lib/routes/changes.js"
        remote_src: yes

    - name: Include secret valued variables for sltt.json
      include_vars: secrets.yml

    - name: Create pm2 config for app
      template:
        src: templates/sltt.json.j2
        dest: "{{sltt}}/sltt.json"

    - name: Create projects db directory
      file:
        path: "{{sltt}}/projects"
        state: directory

    - name: Create videos directory
      file:
        path: "{{sltt}}/videos"
        state: directory

    - name: Start sltt server
      command: pm2 start sltt.json
      args:
        chdir: "{{sltt}}"

    - name: Save service settings
      command: pm2 save
      args:
        chdir: "{{sltt}}"